services:
  db:
    image: postgres:15-alpine
    container_name: obrail_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - obrail_net
    ports:
      - "5432:5432"

  etl:
    build: ./etl
    container_name: obrail_etl
    depends_on:
      - db
    env_file: .env
    environment:
      DATA_DIR: /app/data
      PAN_MAX_FEEDS: 50
      PAN_ONLY_GTFS: "true"
      PAN_ONLY_RAIL: "true"
      RESET_DB: "true"
      TRANSITLAND_ENABLED: "false"
    volumes:
      - ./data:/app/data
    networks:
      - obrail_net

  api:
    build: ./api
    container_name: obrail_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      QUALITY_REPORT_PATH: /app/data/processed/quality_report.json
      MODEL_METRICS_PATH: /app/data/processed/model_metrics.json
    volumes:
      - ./data:/app/data
    networks:
      - obrail_net

  dashboard:
    build: ./dashboard
    container_name: obrail_dashboard
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file: .env
    environment:
      API_URL: http://api:8000
    networks:
      - obrail_net

  

volumes:
  postgres_data:

networks:
  obrail_net:
    driver: bridge
